<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Gemstone.Common" Version="1.0.166" />
    <PackageReference Include="Gemstone.Timeseries" Version="1.0.166" />
    <PackageReference Include="Gemstone.STTP" Version="1.0.631" />
  </ItemGroup>

</Project>
